### ISSUE TITLE
Request Access button on your home page is busted

### ISSUE THREAD

**Issue by theroadeldorado** [juanroldan1989/shaken_not_stirred#2]
Takes to spam not your google form

**Comment by juanroldan1989** [comment]
@theroadeldorado the links within the README file looks good to me 

<img width="941" alt="Screen Shot 2022-01-20 at 16 20 42" src="https://user-images.githubusercontent.com/2252229/150407665-7de21b5f-46b5-4b5c-9bb5-3b3f7173fbd5.png">

Here's the link just in case: https://docs.google.com/forms/d/e/1FAIpQLSdLDslLmbCcSDvs85ys67zcvqtW3IWBmng7O0AcY0YrnXvSlA/viewform

: D
